---
- name: Check Server
  hosts: all
  connection: local
  become: yes
  collections:
    - community.general
  tasks:
  - name: Wait for port 22 to become open and contain "OpenSSH"
    ansible.builtin.wait_for:
      port: 22
      host: 10.1.14.88
      search_regex: OpenSSH
      delay: 20
    connection: local
