---
- name: create vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars.yaml
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      cluster: "{{ vcenter_cluster }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      name: "{{ item }}"
      template: "{{ template_name }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_destination_folder }}"
#      state: "{{ vm_state }}"
      state: powered-off
      wait_for_ip_address: yes
    with_items:
     - test_vm_1
