---
- name: create vm demo
  hosts: all
  become: false
  gather_facts: false
  tasks:
  - name: Basic deploy of a service
    community.general.terraform:
      project_path: '/root/template/terraform'
      state: present
    register: IP
  - name: Test
    ansible.builtin.uri:
      url:  https://10.1.14.12/api/v2/inventories/6/hosts/
      url_username: "admin"
      url_password: "h!h]{bDK7Zg$HxK6?5~,"
      force_basic_auth: yes
      method: POST
      validate_certs: false
      headers:
        Content-Type: application/json
      body_format: json
      body: '{"name": "{{ hostvars.terraform.IP.outputs.public_ip.value }}",
              "variables": "ansible_host: {{ hostvars.terraform.IP.outputs.public_ip.value }}"
            }'
      status_code: 201
