---
- name: create vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      cluster: "{{ vcenter_cluster }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      name: "{{ item }}"
      template: "{{ template_name }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_destination_folder }}"
      state: "{{ vm_state }}"
      networks:
      - name: VM Network
        ip: "{{ ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        type: static
      customization:
        autologon: True
        domain: rhel8.2_test
      wait_for_ip_address: true
    with_items:
     - rhel8.2_test_register_satellite
